version: 1.2
workflows:
  - name: bclconvert-interop-qc_1_3_1-1_21
    subclass: CWL
    primaryDescriptorPath: 
      /.dockstore/bclconvert-interop-qc/1.3.1--1.21/bclconvert-interop-qc__1.3.1--1.21.packed.cwl.json
    readMePath: 
      /.github/catalogue/docs/workflows/bclconvert-interop-qc/1.3.1--1.21/bclconvert-interop-qc__1.3.1--1.21.md
    authors:
      - name: Alexis Lucattini
        email: Alexis.Lucattini@umccr.org
    filters:
      tags:
        - bclconvert-interop-qc/1.3.1--1.21
        - bclconvert-interop-qc/1.3.1--1.21__20240627051309
