import { BamInput } from "../../bam-input/1.0.0/bam-input__1.0.0"
import { CramInput } from "../../cram-input/1.0.0/cram-input__1.0.0"
import { FileProperties as IFile } from "cwl-ts-auto"
import { DragenSnvVariantCallerOptions } from "../../dragen-snv-variant-caller-options/4.4.4/dragen-snv-variant-caller-options__4.4.4"
import {DragenCnvCallerOptions} from "../../dragen-cnv-caller-options/4.4.4/dragen-cnv-caller-options__4.4.4";
import {
	DragenMafConversionOptions
} from "../../dragen-maf-conversion-options/4.4.4/dragen-maf-conversion-options__4.4.4";
import {DragenSvCallerOptions} from "../../dragen-sv-caller-options/4.4.4/dragen-sv-caller-options__4.4.4";
import {
	DragenNirvanaAnnotationOptions
} from "../../dragen-nirvana-annotation-options/4.4.4/dragen-nirvana-annotation-options__4.4.4";
import {
	DragenTargetedCallerOptions
} from "../../dragen-targeted-caller-options/4.4.4/dragen-targeted-caller-options__4.4.4";

export interface DragenWgtsDnaOptionsVariantCallingStage {
	/*
	alignment data: 
	The data from the alignment stage
	*/
	alignment_data: BamInput | CramInput
	tumor_alignment_data?: BamInput | CramInput

	/*
	lic instance id location: 
	Use this option to override the default cloud instance ID location
	*/
	lic_instance_id_location?: string | IFile

	/*
	output directory: 
	Specifies the output directory.
	*/
	output_directory: string

	/*
	output file prefix: 
	Outputs file name prefix to use for all files generated by the pipeline.
	*/
	output_file_prefix: string

	/*
	ref tar: 
	Specifies the tarball containing the reference hash table. If the reference is not already loaded into the DRAGEN card, the option automatically loads the reference.
	Note that the actual dragen command is '--ref-dir' but we first need to download and extract the tarball.
	*/
	ref_tar: IFile

	/*
	variant calling options: 
	Specifies the alignment options. The default value is true.
	*/
	snv_variant_caller_options: DragenSnvVariantCallerOptions

	cnv_caller_options?: DragenCnvCallerOptions
	maf_conversion_options?: DragenMafConversionOptions
	sv_caller_options: DragenSvCallerOptions
	nirvana_annotation_options?: DragenNirvanaAnnotationOptions
	targeted_caller_options?: DragenTargetedCallerOptions
}
