import { FileProperties as IFile } from "cwl-ts-auto"
import { DragenSnvVariantCallerOptions } from "../../dragen-snv-variant-caller-options/4.4.4/dragen-snv-variant-caller-options__4.4.4"
import {DragenCnvCallerOptions} from "../../dragen-cnv-caller-options/4.4.4/dragen-cnv-caller-options__4.4.4";
import {
	DragenMafConversionOptions
} from "../../dragen-maf-conversion-options/4.4.4/dragen-maf-conversion-options__4.4.4";
import {DragenSvCallerOptions} from "../../dragen-sv-caller-options/4.4.4/dragen-sv-caller-options__4.4.4";
import {
	DragenNirvanaAnnotationOptions
} from "../../dragen-nirvana-annotation-options/4.4.4/dragen-nirvana-annotation-options__4.4.4";
import {
	DragenTargetedCallerOptions
} from "../../dragen-targeted-caller-options/4.4.4/dragen-targeted-caller-options__4.4.4";
import {FastqListRowsInput} from "../../fastq-list-rows-input/2.0.0/fastq-list-rows-input__2.0.0";
import {BamInput} from "../../bam-input/1.0.0/bam-input__1.0.0";
import {CramInput} from "../../cram-input/1.0.0/cram-input__1.0.0";
import {
	DragenWgtsAlignmentOptions
} from "../../dragen-wgts-alignment-options/4.4.4/dragen-wgts-alignment-options__4.4.4";
import {DragenTmbOptions} from "../../dragen-tmb-options/4.4.4/dragen-tmb-options__4.4.4";
import {DragenMsiOptions} from "../../dragen-msi-options/4.4.4/dragen-msi-options__4.4.4";
import {DragenMrjdOptions} from "../../dragen-mrjd-options/4.4.4/dragen-mrjd-options__4.4.4";

export interface DragenWgtsDnaOptionsVariantCallingStage {
	/*
	  Naming things (helps for renaming the germline bam afterwards)
    */
	sample_name: string
	tumor_sample_name?: string

	/*
	sequence data:
	The data to be aligned and variant called on
	*/
	sequence_data: FastqListRowsInput | BamInput | CramInput
	tumor_alignment_data?: FastqListRowsInput | BamInput | CramInput

	/*
	lic instance id location: 
	Use this option to override the default cloud instance ID location
	*/
	lic_instance_id_location?: string | IFile

	/*
	output directory: 
	Specifies the output directory.
	*/
	output_directory: string

	/*
	output file prefix: 
	Outputs file name prefix to use for all files generated by the pipeline.
	*/
	output_file_prefix: string

	/*
	ref tar: 
	Specifies the tarball containing the reference hash table. If the reference is not already loaded into the DRAGEN card, the option automatically loads the reference.
	Note that the actual dragen command is '--ref-dir' but we first need to download and extract the tarball.
	*/
	ref_tar: IFile

	/*
	Ora reference: Only required if inputs are in ORA format.
	*/
	ora_reference?: IFile

	/*
	alignment options:
	*/
	alignment_options: DragenWgtsAlignmentOptions

	/*
	variant calling options: 
	Specifies the alignment options. The default value is true.
	*/
	snv_variant_caller_options: DragenSnvVariantCallerOptions

	cnv_caller_options?: DragenCnvCallerOptions
	maf_conversion_options?: DragenMafConversionOptions
	sv_caller_options: DragenSvCallerOptions
	nirvana_annotation_options?: DragenNirvanaAnnotationOptions
	targeted_caller_options?: DragenTargetedCallerOptions
	mrjd_options?: DragenMrjdOptions
	tmb_options?: DragenTmbOptions
	msi_options?: DragenMsiOptions
}
