import { DragenWgtsAlignmentOptions } from "../../dragen-wgts-alignment-options/4.4.4/dragen-wgts-alignment-options__4.4.4"
import { DragenRnaGeneExpressionQuantificationOptions } from "../../dragen-rna-gene-expression-quantification-options/4.4.4/dragen-rna-gene-expression-quantification-options__4.4.4"
import { DragenRnaGeneFusionDetectionOptions } from "../../dragen-rna-gene-fusion-detection-options/4.4.4/dragen-rna-gene-fusion-detection-options__4.4.4"
import { FileProperties as IFile } from "cwl-ts-auto"
import { DragenMafConversionOptions } from "../../dragen-maf-conversion-options/4.4.4/dragen-maf-conversion-options__4.4.4"
import { DragenNirvanaAnnotationOptions } from "../../dragen-nirvana-annotation-options/4.4.4/dragen-nirvana-annotation-options__4.4.4"
import { BamInput } from "../../bam-input/1.0.0/bam-input__1.0.0"
import { CramInput } from "../../cram-input/1.0.0/cram-input__1.0.0"
import { DragenSnvVariantCallerOptions } from "../../dragen-snv-variant-caller-options/4.4.4/dragen-snv-variant-caller-options__4.4.4"
import { DragenRnaSpliceVariantCallerOptions } from "../../dragen-rna-splice-variant-caller-options/4.4.4/dragen-rna-splice-variant-caller-options__4.4.4"

export interface DragenWgtsRnaOptionsVariantCallingStage {
	/*
	alignment options: 
	Specifies the alignment options
	*/
	alignment_options: DragenWgtsAlignmentOptions

	/*
	annotation file: 
	Specifies the annotation file. The annotation file is used to annotate the variants.
	*/
	annotation_file?: IFile

	/*
	rna_gene_expression_quantification_options: 
	Options relating to rna gene expression quantification
	*/
	gene_expression_quantification_options: DragenRnaGeneExpressionQuantificationOptions

	/*
	rna_gene_fusion_detection_options: 
	Options relating to rna gene fusion detection
	*/
	gene_fusion_detection_options: DragenRnaGeneFusionDetectionOptions

	/*
	lic instance id location: 
	Use this option to override the default cloud instance ID location
	*/
	lic_instance_id_location?: string | IFile

	/*
	maf conversion options: 
	Specifies the MAF conversion options
	*/
	maf_conversion_options: DragenMafConversionOptions

	/*
	nirvana annotation options: 
	Specifies the Nirvana annotation options
	*/
	nirvana_annotation_options: DragenNirvanaAnnotationOptions

	/*
	ora reference: 
	Specifies the ora reference. The ora reference is used to annotate the variants.
	Note that the actual dragen command is '--ora-reference' but we first need to download and extract the tarball.
	*/
	ora_reference: IFile

	/*
	output directory: 
	Specifies the output directory.
	*/
	output_directory: string

	/*
	output file prefix: 
	Outputs file name prefix to use for all files generated by the pipeline.
	*/
	output_file_prefix: string

	/*
	ref tar: 
	Specifies the tarball containing the reference hash table. If the reference is not already loaded into the DRAGEN card, the option automatically loads the reference.
	Note that the actual dragen command is '--ref-dir' but we first need to download and extract the tarball.
	*/
	ref_tar: IFile

	/*
	sequence data: 
	The sequence data
	*/
	sequence_data: BamInput | CramInput

	/*
	snv variant calling options: 
	Specifies the snv variant caller options.
	*/
	snv_variant_caller_options: DragenSnvVariantCallerOptions

	/*
	rna_splice_variant_caller_options: 
	Options relating to rna splice variant calling
	*/
	splice_variant_caller_options: DragenRnaSpliceVariantCallerOptions
}
