import { FileProperties as IFile } from "cwl-ts-auto"

export interface CramInput {
	/*
	: 
	
	*/
	cram_input: IFile

	/*
	: 
	Reference file, not always required, particularly if generated by the dragen pipeline,
	then we can use the reference directory.
	*/
	cram_reference?: IFile
}
