cwlVersion: v1.1
class: CommandLineTool

# Extensions
$namespaces:
    s: https://schema.org/
    ilmn-tes: http://platform.illumina.com/rdf/ica/
$schemas:
  - https://schema.org/version/latest/schemaorg-current-http.rdf

# Metadata
s:author:
    class: s:Person
    s:name: Alexis Lucattini
    s:email: Alexis.Lucattini@umccr.org
    s:identifier: https://orcid.org/0000-0001-9754-647X

# ID/Docs
id: multiqc--1.10.1
label: multiqc v(1.10.1)
doc: |
  MultiQC is a reporting tool that parses summary statistics from results and log files generated by
  other bioinformatics tools. MultiQC doesn't run other tools for you -
  it's designed to be placed at the end of analysis pipelines or to be run manually
  when you've finished running your tools.

  When you launch MultiQC, it recursively searches through any provided file paths and finds
  files that it recognises. It parses relevant information from these and generates a single stand-alone
  HTML report file. It also saves a directory of data files with all parsed data for further downstream use.

hints:
    ResourceRequirement:
        ilmn-tes:resources:
            tier: standard
            type: standard
            size: xlarge
        coresMin: 4
        ramMin: 14000
    DockerRequirement:
        dockerPull: quay.io/repository/biocontainers/multiqc:1.10.1--pyhdfd78af_1

baseCommand: ["multiqc"]

inputs:
  # Required inputs
  input_directory:
    label: input directory
    doc: |
      The bcl directory
    type: Directory
    inputBinding:
      position: 100
  output_directory_name:
    label: output directory
    doc: |
      The output directory
    type: string
    inputBinding:
      prefix: "--outdir"
  output_filename:
    label: output filename
    doc: |
      Report filename in html format.
      Defaults to 'multiqc-report.html"
    type: string
    inputBinding:
      prefix: "--filename"
  title:
    label: title
    doc: |
      Report title.
      Printed as page header, used for filename if not otherwise specified.
    type: string
    inputBinding:
      prefix: "--title"
  dummy_file:
    label: dummy file
    doc: |
      testing inputs stream logic
      If used will set input mode to stream on ICA which
      saves having to download the entire input folder
    type: File?
    streamable: true

outputs:
  output_directory:
    label: output directory
    doc: |
      Directory that contains all multiqc analysis data
    type: Directory
    outputBinding:
      glob: "$(inputs.output_directory_name)"
  output_file:
    label: output file
    doc: |
      Output html file
    type: File
    outputBinding:
      glob: "$(inputs.output_directory_name)/$(inputs.output_filename)"

successCodes:
  - 0