cwlVersion: v1.1
class: CommandLineTool

# Extensions
$namespaces:
    s: https://schema.org/
    ilmn-tes: http://platform.illumina.com/rdf/iap/

$schemas:
  - https://schema.org/version/latest/schemaorg-current-http.rdf

# Metadata
s:author:
    class: s:Person
    s:name: Alexis Lucattini
    s:email: Alexis.Lucattini@umccr.org
    s:identifier: https://orcid.org/0000-0001-9754-647X

# ID/Docs
id: multiqc--1.10.1
label: multiqc v(1.10.1)
doc: |
  MultiQC is a reporting tool that parses summary statistics from results and log files generated by
  other bioinformatics tools. MultiQC doesn't run other tools for you -
  it's designed to be placed at the end of analysis pipelines or to be run manually
  when you've finished running your tools.

  When you launch MultiQC, it recursively searches through any provided file paths and finds
  files that it recognises. It parses relevant information from these and generates a single stand-alone
  HTML report file. It also saves a directory of data files with all parsed data for further downstream use.

hints:
    ResourceRequirement:
        ilmn-tes:resources:
            tier: standard
            type: standard
            size: xlarge
        coresMin: 4
        ramMin: 14000
    DockerRequirement:
        dockerPull: quay.io/biocontainers/multiqc:1.10.1--pyhdfd78af_1

requirements:
  InlineJavascriptRequirement:
    expressionLib:
      - var get_input_dir = function(){
          /*
          Just returns the name of the input directory
          */
          return "multiqc_input_dir";
        }
  InitialWorkDirRequirement:
    listing:
      - entryname: run_multiqc.sh
        entry: |
          #!/usr/bin/env bash

          # Set up to fail
          set -euo pipefail

          # Create input dir
          mkdir "$(get_input_dir())"

          # Create an array of dirs
          input_dir_path_array=( $(inputs.input_directories.map(function(a) {return '"' + a.path + '"';}).join(' ')) )
          input_dir_basename_array=( $(inputs.input_directories.map(function(a) {return '"' + a.basename + '"';}).join(' ')) )

          # Iterate through input direcotires
          for input_dir_path in "\${input_dir_path_array[@]}"; do
            ln -s "\${input_dir_path}" "$(get_input_dir())/"
          done

          # Run multiqc
          eval multiqc '"\${@}"'

          # Run ls to see what's here
          ls

          # Unlink input directories - otherwise ICA tries to upload them onto gds (and fails)
          for input_dir_basename in "\${input_dir_basename_array[@]}"; do
            unlink "$(get_input_dir())/\${input_dir_basename}"
          done

          # Run ls to see what's here
          ls

baseCommand: ["bash", "run_multiqc.sh"]

arguments:
  - position: 100
    valueFrom: "$(get_input_dir())"

inputs:
  # Required inputs
  input_directories:
    label: input directories
    doc: |
      The list of directories to place in the analysis
    type: Directory[]
  output_directory_name:
    label: output directory
    doc: |
      The output directory
    type: string
    inputBinding:
      prefix: "--outdir"
      valueFrom: "$(runtime.outdir)/$(self)"
  output_filename:
    label: output filename
    doc: |
      Report filename in html format.
      Defaults to 'multiqc-report.html"
    type: string
    inputBinding:
      prefix: "--filename"
  title:
    label: title
    doc: |
      Report title.
      Printed as page header, used for filename if not otherwise specified.
    type: string
    inputBinding:
      prefix: "--title"
  dummy_file:
    label: dummy file
    doc: |
      testing inputs stream logic
      If used will set input mode to stream on ICA which
      saves having to download the entire input folder
    type: File?
    streamable: true


outputs:
  output_directory:
    label: output directory
    doc: |
      Directory that contains all multiqc analysis data
    type: Directory
    outputBinding:
      glob: "$(inputs.output_directory_name)"
  output_file:
    label: output file
    doc: |
      Output html file
    type: File
    outputBinding:
      glob: "$(inputs.output_directory_name)/$(inputs.output_filename)"

successCodes:
  - 0