name: Create Workflow Release Asset

on:
  push:
    tags:
      - [A-Za-z0-9-_]+/[0-9]+\.[0-9]+\.[0-9]+(?:--\S+)?
      - [A-Za-z0-9-_]+/[0-9]+\.[0-9]+\.[0-9]+(?:--\S+)?(-rc)

jobs:
  create_release:
    name: create release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      # # DEBUG
      # - uses: hmarr/debug-action@v2
      - name: Checkout code
        id: git_checkout
        uses: actions/checkout@v3
      # Set to fail
      - name: Update bash settings
        id: update_bash_settings
        run: |
          set -euo pipefail
      # Get tag
      - name: Set output
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      # Install jq (for querying branch name)
      - name: Install Jq
        id: install_jq
        run: |
          sudo apt-get update -y
          sudo apt-get install jq -y
      # Get date
      - name: get date
        id: get_date
        run: |
          echo "date_str=$(date +%s)" >> "${GITHUB_OUTPUT}"
      # Get is prerelease
      - name: is pre-release
        id: is_prerelease
        run: |
          if [[ "${{ steps.get_tag.outputs.tag }}" =~ .*-rc ]]; then
            echo "is_prerelease="--draft-release" >> "${GITHUB_OUTPUT}"
          else
            echo "is_prelease=''" >> "${GITHUB_OUTPUT}"
          fi
      # Get workflow path
      - name: get workflow path
        id: get_workflow_path
        run: |
          # Get tag without release candidate
          tag="${{ steps.get_tag.outputs.tag }}"
          tag="${tag//-rc}"
          # Check workflow directory exists
          if [[ ! -d "workflows/$tag" ]]; then
            echo "Could not find directory workflows/$tag"
            exit 1
          fi
          workflow_path="$( \
            find "workflows/$tag" \
              -mindepth 1 \
              -maxdepth 1 \
              -type f \
              -name "*.cwl"
          )"
          echo "workflow_path=${workflow_path}" >> "${GITHUB_OUTPUT}"
      # Set git tag env var
      - name: set git tag
        id: set_git_tag
        run: |
          echo "git_tag=${{ steps.get_tag.outputs.tag }},${{ steps.get_tag.outputs.tag }}__${{ steps.get_date.outputs.date_str }}" >> "${GITHUB_OUTPUT}"
      # Set up complete
      # Create release asset
      - name: create release asset
        id: create_release_asset
        run: |
          docker run \
            --rm \
            --user "$(id -u):$(id -g)" \
            --volume "$PWD:$PWD" \
            --workdir "$PWD" \
            --env USER="$(id -u)" \
            --env CWL_ICA_REPO_PATH="${PWD}" \
            --env GITHUB_SERVER_URL="${GITHUB_SERVER_URL}" \
            --env GITHUB_REPOSITORY="${GITHUB_REPOSITORY}" \
            --env GITHUB_TAG="${{ steps.set_git_tag.outputs.git_tag }}" \
            --env GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            ghcr.io/umccr/cwl-ica-cli:latest \
              cwl-ica github-actions-build-workflow-release-asset \
                --workflow-path "${{ steps.get_workflow_path.outputs.workflow_path }}" \
                "${{ steps.is_prerelease.outputs.is_prerelease }}"