name: get-encrypted-tenant-icav2-access-token

on:
  workflow_call:
    inputs:
      role_to_assume_arn:
        required: true
        type: string
      secret_arn:
        required: true
        type: string
    secrets:
      symmetrical_encryption_key:
        required: true
    outputs:
      icav2_access_token_encrypted:
        description: the tenant access token (encrypted with the symmetical encryption key)
        value: ${{ jobs.get_token.outputs.icav2_access_token_encrypted }}

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  get_token:
    name: get-token
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        id: git_checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role_to_assume_arn }}
          aws-region: ap-southeast-2
      - name: Retrieve Secret
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ICAV2_ACCESS_TOKEN, ${{ inputs.secret_arn }}
      - id: encrypt_access_token
        name: Encrypt Access Token
        uses: ./.github/actions/encrypt_token
        with:
          decrypted_token: ${{ env.ICAV2_ACCESS_TOKEN }}
          encryption_key: ${{ secrets.SYMMETRICAL_ENCRYPTION_KEY }}
    outputs:
      icav2_access_token_encrypted: ${{ steps.encrypt_access_token.outputs.encrypted_token }}
